### ISSUE TITLE
关于一些疑惑

### ISSUE THREAD

**Issue by dongliang1993** [beyondxgb/xredux#1]
1.在这个 xredux 库中，是不是 reducer 的作用变得可有可无了？比如我派发一个同步的 action，也完全可以写成一个 effects，在里面调用 setState 来进行 state 的更新。
2. 每个model 里面的 setState 内部实现应该是在轮子了里面自己写了一个 reducer 吧？如果是这样的话，可能还需要注意在每个 model 的 reduer 里面同名的 setState 的 reducer，不然可能会被替换
3. 目前实现的只是数据层么？想要和 react-redux 结合使用，是不是还需要做一些工作？

**Comment by beyondxgb** [comment]
1. 按你这样说是可以的，但不是推荐的，因为 setState 只是为了优化请求状态多的问题，用意不是像你这样想的，同步的 action 希望还是写在 reducers 中，和 redux 保持一致，只有异步 action 才会在 effects 中，setState 其实是个小优化，不太建议滥用，否则会影响 redux 的规范。
2. 是的，你看得挺仔细，在每个 model 会内置一个 setState 的 reducer，但在内置前会判断是否已经有同名的 setState reducer，如果有的话，不会覆盖用户的，这个在文档会和使用者有个约定。
3. 是的，只是数据层，你可以理解它就是 redux 的升级版而已，它可以用在任何 UI 框架中，与 react-redux 的结合使用，和 redux 那边是一样的，你可以看看这个样例工程 https://github.com/risjs/create-ris/tree/master/template/standard
